# Generated by Django 4.2.1 on 2023-06-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('meeting_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('meeting_datetime', models.DateTimeField(blank=True)),
                ('meeting_title', models.CharField(blank=True, max_length=100)),
                ('meeting_organizer', models.CharField(blank=True, max_length=100)),
                ('meeting_type', models.CharField(blank=True, max_length=100)),
                ('meeting_channel', models.CharField(blank=True, max_length=100)),
                ('meeting_participants', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='transcript',
            fields=[
                ('transcript_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('transcript_raw', models.CharField(blank=True, max_length=9999999)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetings')),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
        migrations.CreateModel(
            name='summary',
            fields=[
                ('summary_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('meeting_summary', models.CharField(blank=True, max_length=1000)),
                ('meeting_agenda', models.CharField(blank=True, max_length=500)),
                ('meeting_keypoints', models.CharField(blank=True, max_length=1000)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetings')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
    ]
